//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_WebForms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int EstudianteId { get; set; }
        public decimal NroDocumento { get; set; }
        public string Sobrenombre { get; set; }
        public decimal CantidadAdeudada { get; set; }
    }
}
